//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEU_Examen
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Libros
    {
        [ScaffoldColumn(false)]
        public int id { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Campo requerido"), MaxLength(55)]
        [Display(Name = "Titulo")]
        public string titulo { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Campo requerido"), MaxLength(55)]
        [Display(Name = "Autor")]
        public string autor { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Campo requerido"), MaxLength(55)]
        [Display(Name = "ISBN")]
        public string isbn { get; set; }

        [Display(Name = "Fecha de publicacion")]
        [DisplayFormat(DataFormatString = "{0:dd/MMM/yyyy}")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> fecha_publicacion { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Campo requerido"), MaxLength(55)]
        [Display(Name = "Ejemplares")]
        public Nullable<int> numero_ejemplares { get; set; }

        [Required(ErrorMessage = "El campo es requerida")]
        public Nullable<int> id_categoria { get; set; }
    
        public virtual Categorias Categorias { get; set; }

    }
}
