//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEU_Examen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Videos
    {
        public int id { get; set; }
        public string titulo { get; set; }
        public Nullable<System.DateTime> fecha_publicacion { get; set; }
        public string formato { get; set; }
        public Nullable<int> duracion { get; set; }
        public Nullable<int> id_categoria { get; set; }
    
        public virtual Categorias Categorias { get; set; }
    }
}
